#:import menu menu

MainWidget:

<MainWidget> :
    canvas.before :
        Rectangle :
            size : self.size
            source : "images/IMG_20221126_195144.jpg"
    menu_widget:menu_widget
    perspective_point_x : self.width/2
    perspective_point_y : self.height*0.75      
    MenuWidget:
        id : menu_widget
    Label :
        text : root.score_txt
        font_size : "20dp"
        size_hint : .2,.2
        pos_hint : {"x":0,"top":1}
        color : 0,0,1